from psycopg2 import Error
from Postgres import Postgres
from config_parse import config


#SQL запросы на создание таблиц в БД
create_table_last_post = '''CREATE TABLE last_post (
    website    TEXT    NOT NULL,
    id_post    INT     NOT NULL);'''

create_table_last_post_array = '''CREATE TABLE last_post_array (
    website    TEXT    NOT NULL,
    id_post    INT     ARRAY     NOT NULL);'''

create_table_event = '''CREATE TABLE event (
    id         INT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_parse   INT     NOT NULL,
    type       TEXT    NOT NULL,
    img        TEXT    NOT NULL,
    title      TEXT    NOT NULL,
    data_start TEXT,
    data_stop  TEXT,
    cost       TEXT,
    address    TEXT,
    metro      TEXT,
    link       TEXT
);'''

create_table_user = '''CREATE TABLE user_data (
    id        INT      GENERATED BY DEFAULT AS IDENTITY,
    user_id   INT      NOT NULL,
    status    BOOL     NOT NULL DEFAULT TRUE,
    user_name TEXT
);'''

"""
create_table_logging = '''CREATE TABLE logging (
    id        INT      GENERATED BY DEFAULT AS IDENTITY,
    date   INT      NOT NULL,
        BOOL     NOT NULL DEFAULT TRUE,
    user_name TEXT
);'''
"""
#cc
try:
    conn = Postgres() 
    # создаем основные таблицы
    conn.cursor.execute(create_table_last_post)
    conn.cursor.execute(create_table_event)
    conn.cursor.execute(create_table_user)
    conn.cursor.execute(create_table_last_post_array)
    # заполняем таблицу с сайтами и ключми
    for key, value in config.items():
        conn.add_website_parse(key, 0, value[3])

    conn.add_website_parse('last_event', 0, False)
    
    # добавляем админа
    conn.add_subscriber(435001186, 'Admin')
        
    conn.connection.commit()

    print("Таблицы созданы")

except (Exception, Error) as error:
    print("Таблицы не созданы", error)

finally:
    if conn.connection:
        conn.cursor.close()
        conn.close()
